let div = document.createElement('div');
let textNode = document.createTextNode('Шутки');
document.body.append(div);
div.append(textNode);
let joke1 = document.createElement('joke1');
let j1 = document.createTextNode(' 1. Когда обои клеишь, главное, чтобы пузырей не было. Вот взяли мы как–то два пузыря…');
document.body.append(joke1);
joke1.append(j1);
let p = document.createElement('p');
let j2 = document.createTextNode(' 2. Вчера соседский воробей снова позвал бухать. — Воробьи не умеют разговаривать. Ты — плод моего больного воображения. — Было предложено, и улетел. 09.01.23 читаю: "Птицы объелись забродившей рябины, и валяются по всему городу пьяные.');
document.body.append(p);
p.append(j2);
let p1 = document.createElement('p1');
let j3 = document.createTextNode(' 3. Больница. В палате лежит летчик весь в гипсе, с руками и ногами на подвесках и диктует санитарке письмо: "Уважаемый издатель! На странице 13 вашей инструкции "Как управлять вертолетом" мною была обнаружена опечатка!"...');
document.body.append(p1);
p1.append(j3);
div.classList.add('title');
let title = document.querySelector('.title');
title.style.textAlign = "center";
title.style.fontSize = "44px";